const backgrounds = [
    {
        name: 'Acolyte',
        personalities: [
            `I idolize a particular hero of my faith, and constantly refer to that person's deeds and example.`,
            `I can find common ground between the fiercest enemies, empathizing with them and always working toward peace.`,
            `I see omens in every event and action. The gods try to speak to us, we just need to listen.`,
            `Nothing can shake my optimistic attitude.`,
            `I quote (or misquote) sacred texts and proverbs in almost every situation.`,
            `I am tolerant (or intolerant) of other faiths and respect (or condemn) the worship of other gods.`,
            `I've enjoyed fine food, drink, and high society among my temple's elite. Rough living grates on me.`,
            `I've spent so long in the temple that I have little practical experience dealing with people in the outside world.`,
        ],
        ideals: [
            `Tradition. The ancient traditions of worship and sacrifice must be preserved and upheld. (Lawful)`,
            `Charity. I always try to help those in need, no matter what the personal cost. (Good)`,
            `Change. We must help bring about the changes the gods are constantly working in the world. (Chaotic)`,
            `Power. I hope to one day rise to the top of my faith's religious hierarchy. (Lawful)`,
            `Faith. I trust that my deity will guide my actions. I have faith that if I work hard, things will go well. (Lawful)`,
            `Aspiration. I seek to prove myself worthy of my god's favor by matching my actions against their teachings. (Any)`,
        ], 
        bonds: [
            `I would die to recover an ancient relic of my faith that was lost long ago.`,
            `I will someday get revenge on the corrupt temple hierarchy who branded me a heretic.`,
            `I owe my life to the priest who took me in when my parents died.`,
            `Everything I do is for the common people.`,
            `I will do anything to protect the temple where I served.`,
            `I seek to preserve a sacred text that my enemies consider heretical and seek to destroy.`,
        ],
        flaws: [
            `I judge others harshly, and myself even more severely.`,
            `I put too much trust in those who wield power within my temple's hierarchy.`,
            `My piety sometimes leads me to blindly trust those that profess faith in my god.`,
            `I am inflexible in my thinking.`,
            `I am suspicious of strangers and expect the worst of them.`,
            `Once I pick a goal, I become obsessed with it to the detriment of everything else in my life.`,
            ]
    },
    {
        name: 'Anthropologist',
        personalities: [
            `I prefer the company of those who aren't like me, including people of other races.`,
            `I'm a stickler when it comes to observing proper etiquette and local customs.`,
            `I would rather observe than meddle.`,
            `By living among violent people, I have become desensitized to violence.`,
            `I would risk life and limb to discover a new culture or unravel the secrets of a dead one.`,
            `When I arrive at a new settlement for the first time, I must learn all its customs.`,
        ],
        ideals: [
            `Discovery. I want to be the first person to discover a lost culture. (Any)`,
            `Distance. One must not interfere with the affairs of another culture – even one in need of aid. (Lawful)`,
            `Knowledge. By understanding other races and cultures, we learn to understand ourselves. (Any)`,
            `Power. Common people crave strong leadership, and I do my utmost to provide it. (Lawful)`,
            `Protection. I must do everything possible to save a society facing extinction. (Good)`,
            `Indifferent. Life is cruel. What's the point in saving people if they're going to die anyway? (Chaotic)`,
        ],
        bonds: [
            `My mentor gave me a journal filled with lore and wisdom. Losing it would devastate me.`,
            `Having lived among the people of a primeval tribe or clan, I long to return and see how they are faring.`,
            `Years ago, tragedy struck the members of an isolated society I befriended, and I will honor them.`,
            `I want to learn more about a particular humanoid culture that fascinates me.`,
            `I seek to avenge a clan, tribe, kingdom, or empire that was wiped out.`,
            `I have a trinket that I believe is the key to finding a long-lost society.`,
        ],
        flaws: [
            `Boats make me seasick.`,
            `I talk to myself, and I don't make friends easily.`,
            `I believe that I'm intellectually superior to people from other cultures and have much to teach them.`,
            `I've picked up some unpleasant habits living among races such as goblins, lizardfolk, or orcs.`,
            `I complain about everything.`,
            `I wear a tribal mask and never take it off.`,
        ]
    },
    {
        name: 'Archaeologist',
        personalities: [
            `I love a good puzzle or mystery.`,
            `I'm a pack rat who never throws anything away.`,
            `Fame is more important to me than money.`,
            `I have no qualms about stealing from the dead.`,
            `I'm happier in a dusty old tomb than I am in the centers of civilization.`,
            `Traps don't make me nervous. Idiots who trigger traps make me nervous.`,
            `I might fail, but I will never give up.`,
            `You might think I'm a scholar, but I love a good brawl. These fists were made for punching.`,
        ],
        ideals: [
            `Preservation. That artifact belongs in a museum. (Good)`,
            `Greed. I won't risk my life for nothing. I expect some kind of payment. (Any)`,
            `Death Wish. Nothing is more exhilarating than a narrow escape from the jaws of death. (Chaotic)`,
            `Dignity. The dead and their belongings deserve to be treated with respect. (Lawful)`,
            `Immortality. All my exploring is part of a plan to find the secret of everlasting life. (Any)`,
            `Danger. With every great discovery comes grave danger. The two walk hand in hand. (Any)`,
        ], 
        bonds: [
            `Ever since I was a child, I've heard stories about a lost city. I aim to find it, learn its secrets, and earn my place in the history books.`,
            `I want to find my mentor, who disappeared on an expedition some time ago.`,
            `I have a friendly rival. Only one of us can be the best, and I aim to prove it's me.`,
            `I won't sell an art object or other treasure that has historical significance or is one of a kind.`,
            `I'm secretly in love with the wealthy patron who sponsors my archaeological exploits.`,
            `I hope to bring prestige to a library, a museum, or a university.`,
        ],
        
        flaws: [
            `I have a secret fear of some common wild animal – and in my work, I see them everywhere.`,
            `I can't leave a room without searching it for secret doors.`,
            `When I'm not exploring dungeons or ruins, I get jittery and impatient.`,
            `I have no time for friends or family. I spend every waking moment thinking about and preparing for my next expedition.`,
            `When given the choice of going left or right, I always go left.`,
            `I can't sleep except in total darkness.`,
        ]
    },
    {
        name: 'Athlete',
        personalities: [
            `I feel most at peace during physical exertion, whether exercise or battle.`,
            `I don't like to sit idle.`,
            `I have a daily exercise routine I refuse to break.`,
            `Obstacles exist to be overcome.`,
            `When I see others struggling, I offer to help.`,
            `I love to trade banter and gibes.`,
            `Anything worth doing is worth doing best.`,
            `I get irritated if people praise someone else and not me.`,
        ],
        ideals: [
            `Competition. I strive to test myself in all things. (Chaotic)`,
            `Triumph. The best part of winning is seeing my rivals brought low. (Evil)`,
            `Camaraderie. The strongest bonds are forged through struggle. (Good)`,
            `People. I strive to inspire my spectators. (Neutral)`,
            `Tradition. Every game has rules, and the playing field must be level. (Lawful)`,
            `Growth. Lessons hide in victory and defeat. (Any)`,
        ],
        bonds: [
            `My teammates are my family.`,
            `I will overcome a rival and prove myself their better.`,
            `My mistake got someone hurt. Ill never make that mistake again.`,
            `I will be the best for the honor and glory of my home.`,
            `The person who trained me is the most important person in my world.`,
            `I strive to live up to a specific hero's example.`,
        ], 
        flaws: [
            `I indulge in a habit that threatens my reputation or health.`,
            `I'll do absolutely anything to win.`,
            `I ignore anyone who doesn't compete and anyone who loses to me.`,
            `I have lingering pain of old injuries.`,
            `Any defeat or failure on my part is because my opponents cheated.`,
            `I must be the captain of any group I join.`,
        ]
    },
    {
        name: 'Charlatan',
        personalities: [
            `I fall in and out of love easily, and am always pursuing someone.`,
            `I have a joke for every occasion, especially occasions where humor is inappropriate.`,
            `Flattery is my preferred trick for getting what I want.`,
            `I'm a born gambler who can't resist taking a risk for a potential payoff.`,
            `I lie about almost everything, even when there's no good reason to.`,
            `Sarcasm and insults are my weapons of choice.`,
            `I keep multiple holy symbols on me and invoke whatever deity might come in useful at any given moment.`,
            `I pocket anything I see that might have some value.`,
        ],    
        ideals: [
            `Independence. I am a free spirit – no one tells me what to do. (Chaotic)`,
            `Fairness. I never target people who can't afford to lose a few coins. (Lawful)`,
            `Charity. I distribute the money I acquire to the people who really need it. (Good)`,
            `Creativity. I never run the same con twice. (Chaotic)`,
            `Friendship. Material goods come and go. Bonds of friendship last forever. (Good)`,
            `Aspiration. I'm determined to make something of myself. (Any)`,
        ],
        bonds: [
            `I fleeced the wrong person and must work to ensure that this individual never crosses paths with me or those I care about.`,
            `I owe everything to my mentor – a horrible person who's probably rotting in jail somewhere.`,
            `Somewhere out there, I have a child who doesn't know me. I'm making the world better for him or her.`,
            `I come from a noble family, and one day I'll reclaim my lands and title from those who stole them from me.`,
            `A powerful person killed someone I love. Some day soon, I'll have my revenge.`,
            `I swindled and ruined a person who didn't deserve it. I seek to atone for my misdeeds but might never be able to forgive myself.`,
        ],
        flaws: [
            `I can't resist a pretty face.`,
            `I'm always in debt. I spend my ill-gotten gains on decadent luxuries faster than I bring them in.`,
            `I'm convinced that no one could ever fool me the way I fool others.`,
            `I'm too greedy for my own good. I can't resist taking a risk if there's money involved.`,
            `I can't resist swindling people who are more powerful than me.`,
            `I hate to admit it and will hate myself for it, but I'll run and preserve my own hide if the going gets tough.`,
        ]
    },
    {
        name: 'Criminal',
        personalities: [
            `I always have a plan for what to do when things go wrong.`,
            `I am always calm, no matter what the situation. I never raise my voice or let my emotions control me.`,
            `The first thing I do in a new place is note the locations of everything valuable – or where such things could be hidden.`,
            `I would rather make a new friend than a new enemy.`,
            `I am incredibly slow to trust. Those who seem the fairest often have the most to hide.`,
            `I don't pay attention to the risks in a situation. Never tell me the odds.`,
            `The best way to get me to do something is to tell me I can't do it.`,
            `I blow up at the slightest insult.`,
        ],
        ideals: [
            `Honor. I don't steal from others in the trade. (Lawful)`,
            `Freedom. Chains are meant to be broken, as are those who would forge them. (Chaotic)`,
            `Charity. I steal from the wealthy so that I can help people in need. (Good)`,
            `Greed. I will do whatever it takes to become wealthy. (Evil)`,
            `People. I'm loyal to my friends, not to any ideals, and everyone else can take a trip down the Styx for all I care. (Neutral)`,
            `Redemption. There's a spark of good in everyone. (Good)`,
        ],  
        bonds: [
            `I'm trying to pay off an old debt I owe to a generous benefactor.`,
            `My ill-gotten gains go to support my family.`,
            `Something important was taken from me, and I aim to steal it back.`,
            `I will become the greatest thief that ever lived.`,
            `I'm guilty of a terrible crime. I hope I can redeem myself for it.`,
            `Someone I loved died because of I mistake I made. That will never happen again.`,
        ],
        flaws: [
            `When I see something valuable, I can't think about anything but how to steal it.`,
            `When faced with a choice between money and my friends, I usually choose the money.`,
            `If there's a plan, I'll forget it. If I don't forget it, I'll ignore it.`,
            `I have a "tell" that reveals when I'm lying.`,
            `I turn tail and run when things look bad.`,
            `An innocent person is in prison for a crime that I committed. I'm okay with that.`,
        ]
    },
    {
        name: 'Entertainer',
        personalities: [
            `I know a story relevant to almost every situation.`,
            `Whenever I come to a new place, I collect local rumors and spread gossip.`,
            `I'm a hopeless romantic, always searching for that "special someone."`,
            `Nobody stays angry at me or around me for long, since I can defuse any amount of tension.`,
            `I love a good insult, even one directed at me.`,
            `I get bitter if I'm not the center of attention.`,
            `I'll settle for nothing less than perfection.`,
            `I change my mood or my mind as quickly as I change key in a song.`,
        ],
        ideals: [
            `Beauty. When I perform, I make the world better than it was. (Good)`,
            `Tradition. The stories, legends, and songs of the past must never be forgotten, for they teach us who we are. (Lawful)`,
            `Creativity. The world is in need of new ideas and bold action. (Chaotic)`,
            `Greed. I'm only in it for the money and fame. (Evil)`,
            `People. I like seeing the smiles on people's faces when I perform. That's all that matters. (Neutral)`,
            `Honesty. Art should reflect the soul; it should come from within and reveal who we really are. (Any)`,
        ],  
        bonds: [
            `My instrument is my most treasured possession, and it reminds me of someone I love.`,
            `Someone stole my precious instrument, and someday I'll get it back.`,
            `I want to be famous, whatever it takes.`,
            `I idolize a hero of the old tales and measure my deeds against that person's.`,
            `I will do anything to prove myself superior to my hated rival.`,
            `I would do anything for the other members of my old troupe.`,
        ],
        flaws: [
            `I'll do anything to win fame and renown.`,
            `I'm a sucker for a pretty face.`,
            `A scandal prevents me from ever going home again. That kind of trouble seems to follow me around.`,
            `I once satirized a noble who still wants my head. It was a mistake that I will likely repeat.`,
            `I have trouble keeping my true feelings hidden. My sharp tongue lands me in trouble.`,
            `Despite my best efforts, I am unreliable to my friends.`,
        ]
    },
    {
        name: 'Faceless',
        personalities: [
            `I'm earnest and uncommonly direct.`,
            `I strive to have no personality—it's easier to forget what's hardly there.`,
            `I treasure a memento of a person or instance that set me upon my path.`,
            `I sleep just as much as I need to and on an unusual schedule.`,
            `I think far ahead, a detachedness often mistaken for daydreaming.`,
            `I cultivate a single obscure hobby or study and eagerly discuss it at length.`,
            `I am ever learning how to be among others—when to stay quiet, when to laugh.`,
            `I behave like an extreme opposite of my persona.`,
        ],
        ideals: [
            `Justice. Place in society shouldn't determine one's access to what is right. (Good)`,
            `Security. Doing what must be done can't bring the innocent to harm. (Lawful)`,
            `Confusion. Deception is a weapon. Strike from where your foes won't expect. (Chaotic)`,
            `Infamy. My name will be a malediction, a curse that fulfills my will. (Evil)`,
            `Incorruptibility. Be a symbol, and leave your flawed being behind. (Any)`,
            `Anonymity. It's my deeds that should be remembered, not their instrument. (Any)`,
        ],  
        bonds: [
            `I do everything for my family. My first thought is keeping them safe.`,
            `What I do, I do for the world. The people don't realize how much they need me.`,
            `I've seen too many in need. I must not fail them as everyone else has.`,
            `I stand in opposition, lest the wicked go unopposed.`,
            `I am exceptional. I do this because no one else can, and no one can stop me.`,
            `I do everything for those who were taken from me.`,
        ],
        flaws: [
            `I an callous about death. It comes to us all eventually.`,
            `I never make eye contact or hold it unflinchingly.`,
            `I have no sense of humor. Laughing is uncomfortable and embarrassing.`,
            `I overexert myself, sometimes needing to recuperate for a day or more.`,
            `I think far ahead, a detachedness often mistaken for daydreaming.`,
            `I see morality entirely in black and white.`,
        ]
    },
    {
        name: 'Far Traveler',
        personalities: [
            `I have different assumptions from those around me concerning personal space, blithely invading others' space in innocence, or reacting to ignorant invasion of my own.`,
            `I have my own ideas about what is and is not food, and I find the eating habits of those around me fascinating, confusing, or revolting.`,
            `I have a strong code of honor or sense of propriety that others don't comprehend.`,
            `I express affection or contempt in ways that are unfamiliar to others.`,
            `I honor my deities through practices that are foreign to this land.`,
            `I begin or end my day with small traditional rituals that are unfamiliar to those around me.`,
        ],
        ideals: [
            `Open. I have much to learn from the kindly folk I meet along my way. (Good)`,
            `Reserved. As someone new to these strange lands, I am cautious and respectful in my dealings. (Lawful)`,
            `Adventure. I'm far from home, and everything is strange and wonderful! (Chaotic)`,
            `Cunning. Though I may not know their ways, neither do they know mine, which can be to my advantage. (Evil)`,
            `Inquisitive. Everything is new, but I have a thirst to learn. (Neutral)`,
            `Suspicious. I must be careful, for I have no way of telling friend from foe here. (Any)`,
        ],
        bonds: [
            `So long as I have this token from my homeland, I can face any adversity in this strange land.`,
            `The gods of my people are a comfort to me so far from home.`,
            `I hold no greater cause than my service to my people.`,
            `My freedom is my most precious possession. I'll never let anyone take it from me again.`,
            `I'm fascinated by the beauty and wonder of this new land.`,
            `Though I had no choice, I lament having to leave my loved ones behind. I hope to see them again one day.`,
        ],
        flaws: [
            `I am secretly (or not so secretly) convinced of the superiority of my own culture over that of this foreign land.`,
            `I pretend not to understand the local language in order to avoid interactions I would rather not have.`,
            `I have a weakness for the new intoxicants and other pleasures of this land.`,
            `I don't take kindly to some of the actions and motivations of the people of this land, because these folk are different from me.`,
            `I consider the adherents of other gods to be deluded innocents at best, or ignorant fools at worst.`,
            `I have a weakness for the exotic beauty of the people of these lands.`,
        ]
    },
    {
        name: 'Feylost',
        personalities: [
            `I'm haunted by fey laughter that only I can hear, though I know it's just my mind playing tricks on me.`,
            `Like a nomad, I can't settle down in one place for very long.`,
            `Good music makes me weep like a baby.`,
            `Wherever I go, I try to bring a little of the warmth and tranquility of home with me.`,
            `I have never lost my childlike sense of wonder.`,
            `When I have a new idea, I get wildly excited about it until I come up with another, better idea.`,
            `I live by my own set of weird and wonderful rules.`,
            `I can't bring myself to trust most adults.`,
        ],
    
        ideals: [
            `Friendship. I never leave a friend behind. (Good)`,
            `Empathy. No creature should be made to suffer. (Good)`,
            `Wanderlust. I prefer to take the less traveled path. (Chaotic)`,
            `Changeability. Change is good, which is why I live by an ever-changing set of rules. (Chaotic)`,
            `Honor. A deal is a deal, and I would never break one. (Lawful)`,
            `Rule of Three. Everything in the multiverse happens in threes. I see the "rule of three" everywhere. (Lawful)`,
            `Obsession. I won't let go of a grudge. (Evil)`,
            `Greed. I will do whatever it takes to get what I want, regardless of the harm it might cause. (Evil)`,
        ],
        bonds: [
            `I would never break my word.`,
            `I find magic in all its forms to be compelling. The more magical a place, the more I am drawn to it.`,
            `I do what I can to protect the natural world.`,
            `A trusted friend is the most important thing in the multiverse to me.`,
            `I can't bring myself to harm a Fey creature, either because I consider myself one or because I fear the repercussions.`,
            `The Witchlight Carnival feels like home to me.`,
            `I'm drawn to the Feywild and long to return there, if only for a short while.`,
            `I feel indebted to Mister Witch and Mister Light for giving me a home and a purpose.`,
        ],
        flaws: [
            `I easily lose track of time. My poor sense of time means I'm always late.`,
            `I think the whole multiverse is out to get me.`,
            `I'm always operating under a tight timeline, and I'm obsessed with keeping everything on schedule.`,
            `I'm a kleptomaniac who covets shiny, sparkling treasure.`,
            `I'm forgetful. Sometimes I can't remember even the simplest things.`,
            `I never give away anything for free and always expect something in return.`,
            `I have many vices and tend to indulge them.`,
            `I'm always changing my mind-well, almost always.`,
        ]
    },
    {
        name: 'Fisher',
        personalities: [
            `I am unmoved by the wrath of nature.`,
            `My friends are my crew; we sink or float together.`,
            `I need long stretches of quiet to clear my head.`,
            `Rich folk don't know the satisfaction of hard work.`,
            `I laugh heartily, feel deeply, and fear nothing.`,
            `I work hard; nature offers no handouts.`,
            `I dislike bargaining; state your price and mean it.`,
            `Luck favors me, and I take risks others might not.`,
        ],        
        ideals: [
            `Camaraderie. Good people make even the longest voyage bearable. (Good)`,
            `Luck. Our luck depends on respecting its rules—now throw this salt over your shoulder. (Lawful)`,
            `Daring. The richest bounty goes to those who risk everything. (Chaotic)`,
            `Plunder. Take all that you can and leave nothing for the scavengers. (Evil)`,
            `Balance. Do not fish the same spot twice in a row; suppress your greed, and nature will reward you. (Neutral)`,
            `Hard Work. No wave can move a soul hard at work. (Any)`,
        ],  
        bonds: [
            `I lost something important in the deep sea, and I intend to find it.`,
            `Someone else's greed destroyed my livelihood, and I will be compensated.`,
            `I will fish the many famous waters of this land.`,
            `The gods saved me during a terrible storm, and I will honor their gift.`,
            `My destiny awaits me at the bottom of a particular pond in the Feywild.`,
            `I must repay my village's debt.`,
        ],
        flaws: [
            `I am judgmental, especially of those I deem homebodies or otherwise lazy.`,
            `I become depressed and anxious if I'm away from the sea too long.`,
            `I have lived a hard life and find it difficult to empathize with others.`,
            `I am inclined to tell long-winded stories at inopportune times.`,
            `I work hard, but I play harder.`,
            `I am obsessed with catching an elusive aquatic beast, often to the detriment of other pursuits.`,
        ]
    },
    {
        name: 'Folk Hero',
        personalities: [
            `I judge people by their actions, not their words.`,
            `If someone is in trouble, I'm always ready to lend help.`,
            `When I set my mind to something, I follow through no matter what gets in my way.`,
            `I have a strong sense of fair play and always try to find the most equitable solution to arguments.`,
            `I'm confident in my own abilities and do what I can to instill confidence in others.`,
            `Thinking is for other people. I prefer action.`,
            `I misuse long words in an attempt to sound smarter.`,
            `I get bored easily. When am I going to get on with my destiny?`,
        ],        
        ideals: [
            `Respect. People deserve to be treated with dignity and respect. (Good)`,
            `Fairness. No one should get preferential treatment before the law, and no one is above the law. (Lawful)`,
            `Freedom. Tyrants must not be allowed to oppress the people. (Chaotic)`,
            `Might. If I become strong, I can take what I want – what I deserve. (Evil)`,
            `Sincerity. There's no good in pretending to be something I'm not. (Neutral)`,
            `Destiny. Nothing and no one can steer me away from my higher calling. (Any)`,
        ],  
        bonds: [
            `I have a family, but I have no idea where they are. One day, I hope to see them again.`,
            `I worked the land, I love the land, and I will protect the land.`,
            `A proud noble once gave me a horrible beating, and I will take my revenge on any bully I encounter.`,
            `My tools are symbols of my past life, and I carry them so that I will never forget my roots.`,
            `I protect those who cannot protect themselves.`,
            `I wish my childhood sweetheart had come with me to pursue my destiny.`,
        ],
        flaws: [
            `The tyrant who rules my land will stop at nothing to see me killed.`,
            `I'm convinced of the significance of my destiny, and blind to my shortcomings and the risk of failure.`,
            `The people who knew me when I was young know my shameful secret, so I can never go home again.`,
            `I have a weakness for the vices of the city, especially hard drink.`,
            `Secretly, I believe that things would be better if I were a tyrant lording over the land.`,
            `I have trouble trusting in my allies.`,
        ]
    },
    {
        name: 'Giant Foundling',
        personalities: [
            `What I lack in stature, I make up for with sheer spite.`,
            `I insist on being taken seriously as a full-grown adult. Nobody talks down to me!`,
            `Crowded spaces make me uncomfortable. I'd much rather be in a wide-open field than a bustling tavern.`,
            `I embrace my shorter stature. It helps me stay unnoticed—and underestimated.`,
            `Every avalanche begins as a single pebble.`,
            `The world always feels too big, and I'm afraid I'll never find my place in it.`,
        ],
    },
    {
        name: 'Gladiator',
        personalities: [
            `I know a story relevant to almost every situation.`,
            `Whenever I come to a new place, I collect local rumors and spread gossip.`,
            `I'm a hopeless romantic, always searching for that "special someone."`,
            `Nobody stays angry at me or around me for long, since I can defuse any amount of tension.`,
            `I love a good insult, even one directed at me.`,
            `I get bitter if I'm not the center of attention.`,
            `I'll settle for nothing less than perfection.`,
            `I change my mood or my mind as quickly as I change key in a song.`,
        ],        
        ideals: [
            `Beauty. When I perform, I make the world better than it was. (Good)`,
            `Tradition. The stories, legends, and songs of the past must never be forgotten, for they teach us who we are. (Lawful)`,
            `Creativity. The world is in need of new ideas and bold action. (Chaotic)`,
            `Greed. I'm only in it for the money and fame. (Evil)`,
            `People. I like seeing the smiles on people's faces when I perform. That's all that matters. (Neutral)`,
            `Honesty. Art should reflect the soul; it should come from within and reveal who we really are. (Any)`,
        ],  
        bonds: [
            `My instrument is my most treasured possession, and it reminds me of someone I love.`,
            `Someone stole my precious instrument, and someday I'll get it back.`,
            `I want to be famous, whatever it takes.`,
            `I idolize a hero of the old tales and measure my deeds against that person's.`,
            `I will do anything to prove myself superior to my hated rival.`,
            `I would do anything for the other members of my old troupe.`,
        ],
        flaws: [
            `I'll do anything to win fame and renown.`,
            `I'm a sucker for a pretty face.`,
            `A scandal prevents me from ever going home again. That kind of trouble seems to follow me around.`,
            `I once satirized a noble who still wants my head. It was a mistake that I will likely repeat.`,
            `I have trouble keeping my true feelings hidden. My sharp tongue lands me in trouble.`,
            `Despite my best efforts, I am unreliable to my friends.`,
        ]
    },
    {
        name: 'Guild Artisan',
        personalities: [
            `I believe that anything worth doing is worth doing right. I can't help it – I'm a perfectionist.`,
            `I'm a snob who looks down on those who can't appreciate fine art.`,
            `I always want to know how things work and what makes people tick.`,
            `I'm full of witty aphorisms and have a proverb for every occasion.`,
            `I'm rude to people who lack my commitment to hard work and fair play.`,
            `I like to talk at length about my profession.`,
            `I don't part with my money easily and will haggle tirelessly to get the best deal possible.`,
            `I'm well known for my work, and I want to make sure everyone appreciates it. I'm always taken aback when people haven't heard of me.`,
        ],        
        ideals: [
            `Community. It is the duty of all civilized people to strengthen the bonds of community and the security of civilization. (Lawful)`,
            `Generosity. My talents were given to me so that I could use them to benefit the world. (Good)`,
            `Freedom. Everyone should be free to pursue his or her own livelihood. (Chaotic)`,
            `Greed. I'm only in it for the money. (Evil)`,
            `People. I'm committed to the people I care about, not to ideals. (Neutral)`,
            `Aspiration. I work hard to be the best there is at my craft. (Any)`,
        ],  
        bonds: [
            `The workshop where I learned my trade is the most important place in the world to me.`,
            `I created a great work for someone, and then found them unworthy to receive it. I'm still looking for someone worthy.`,
            `I owe my guild a great debt for forging me into the person I am today.`,
            `I pursue wealth to secure someone's love.`,
            `One day I will return to my guild and prove that I am the greatest artisan of them all.`,
            `I will get revenge on the evil forces that destroyed my place of business and ruined my livelihood.`,
        ],
        flaws: [
            `I'll do anything to get my hands on something rare or priceless.`,
            `I'm quick to assume that someone is trying to cheat me.`,
            `No one must ever learn that I once stole money from guild coffers.`,
            `I'm never satisfied with what I have - I always want more.`,
            `I would kill to acquire a noble title.`,
            `I'm horribly jealous of anyone who can outshine my handiwork. Everywhere I go, I'm surrounded by rivals.`,
        ]
    },
    {
        name: 'Guild Merchant',
        personalities: [
            `I believe that anything worth doing is worth doing right. I can't help it - I'm a perfectionist.`,
            `I'm a snob who looks down on those who can't appreciate fine art.`,
            `I always want to know how things work and what makes people tick.`,
            `I'm full of witty aphorisms and have a proverb for every occasion.`,
            `I'm rude to people who lack my commitment to hard work and fair play.`,
            `I like to talk at length about my profession.`,
            `I don't part with my money easily and will haggle tirelessly to get the best deal possible.`,
            `I'm well known for my work, and I want to make sure everyone appreciates it. I'm always taken aback when people haven't heard of me.`,
        ],        
        ideals: [
            `Community. It is the duty of all civilized people to strengthen the bonds of community and the security of civilization. (Lawful)`,
            `Generosity. My talents were given to me so that I could use them to benefit the world. (Good)`,
            `Freedom. Everyone should be free to pursue his or her own livelihood. (Chaotic)`,
            `Greed. I'm only in it for the money. (Evil)`,
            `People. I'm committed to the people I care about, not to ideals. (Neutral)`,
            `Aspiration. I work hard to be the best there is at my craft. (Any)`,
        ],  
        bonds: [
            `The workshop where I learned my trade is the most important place in the world to me.`,
            `I created a great work for someone, and then found them unworthy to receive it. I'm still looking for someone worthy.`,
            `I owe my guild a great debt for forging me into the person I am today.`,
            `I pursue wealth to secure someone's love.`,
            `One day I will return to my guild and prove that I am the greatest artisan of them all.`,
            `I will get revenge on the evil forces that destroyed my place of business and ruined my livelihood.`,
        ],
        flaws: [
            `I'll do anything to get my hands on something rare or priceless.`,
            `I'm quick to assume that someone is trying to cheat me.`,
            `No one must ever learn that I once stole money from guild coffers.`,
            `I'm never satisfied with what I have – I always want more.`,
            `I would kill to acquire a noble title.`,
            `I'm horribly jealous of anyone who can outshine my handiwork. Everywhere I go, I'm surrounded by rivals.`,
        ]
    },
    {
        name: 'Haunted One',
        personalities: [
            `I don't run from evil. Evil runs from me.`,
            `I like to read and memorize poetry. It keeps me calm and brings me fleeting moments of happiness.`,
            `I spend money freely and live life to the fullest, knowing that tomorrow I might die.`,
            `I live for the thrill of the hunt.`,
            `I don't talk about the thing that torments me. I'd rather not burden others with my curse.`,
            `I expect danger around every corner.`,
            `I refuse to become a victim, and I will not allow others to be victimized.`,
            `I put no trust in divine beings.`,
        ],        
        ideals: [
            `Selflessness. I try to help those in need, no matter what the personal cost. (Good)`,
            `Determination. I'll stop the spirits that haunt me or die trying. (Any)`,
            `Greater Good. I kill monsters to make the world a safer place, and to exorcise my own demons. (Good)`,
            `Freedom. I have a dark calling that puts me above the law. (Chaotic)`,
            `Logic. I like to know my enemy's capabilities and weaknesses before rushing into battle. (Lawful)`,
            `Destruction. I'm a monster that destroys other monsters, and anything else that gets in my way. (Evil)`,
        ],  
        bonds: [
            `I keep my thoughts and discoveries in a journal. My journal is my legacy.`,
            `I would sacrifice my life and my soul to protect the innocent.`,
            `My torment drove away the person I love. I strive to win back the love I've lost.`,
            `A terrible guilt consumes me. I hope that I can find redemption through my actions.`,
            `There's evil in me, I can feel it. It must never be set free.`,
            `I have a child to protect. I must make the world a safer place for them.`,
        ],
        flaws: [
            `I have certain rituals that I must follow every day. I can never break them.`,
            `I assume the worst in people.`,
            `I feel no compassion for the dead. They’re the lucky ones.`,
            `I have an addiction.`,
            `I am a purveyor of doom and gloom who lives in a world without hope.`,
            `I talk to spirits that no one else can see.`,
        ]
    },
    {
        name: 'Hermit',
        personalities: [
            `I've been isolated for so long that I rarely speak, preferring gestures and the occasional grunt.`,
            `I am utterly serene, even in the face of disaster.`,
            `The leader of my community had something wise to say on every topic, and I am eager to share that wisdom.`,
            `I feel tremendous empathy for all who suffer.`,
            `I'm oblivious to etiquette and social expectations.`,
            `I connect everything that happens to me to a grand, cosmic plan.`,
            `I often get lost in my own thoughts and contemplation, becoming oblivious to my surroundings.`,
            `I am working on a grand philosophical theory and love sharing my ideas.`,
        ],        
        ideals: [
            `Greater Good. My gifts are meant to be shared with all, not used for my own benefit. (Good)`,
            `Logic. Emotions must not cloud our sense of what is right and true, or our logical thinking. (Lawful)`,
            `Free Thinking. Inquiry and curiosity are the pillars of progress. (Chaotic)`,
            `Power. Solitude and contemplation are paths toward mystical or magical power. (Evil)`,
            `Live and Let Live. Meddling in the affairs of others only causes trouble. (Neutral)`,
            `Self-Knowledge. If you know yourself, there's nothing left to know. (Any)`,
        ],  
        bonds: [
            `Nothing is more important than the other members of my hermitage, order, or association.`,
            `I entered seclusion to hide from the ones who might still be hunting me. I must someday confront them.`,
            `I'm still seeking the enlightenment I pursued in my seclusion, and it still eludes me.`,
            `I entered seclusion because I loved someone I could not have.`,
            `Should my discovery come to light, it could bring ruin to the world.`,
            `My isolation gave me great insight into a great evil that only I can destroy.`,
        ],
        flaws: [
            `Now that I've returned to the world, I enjoy its delights a little too much.`,
            `I harbor dark, bloodthirsty thoughts that my isolation and meditation failed to quell.`,
            `I am dogmatic in my thoughts and philosophy.`,
            `I let my need to win arguments overshadow friendships and harmony.`,
            `I'd risk too much to uncover a lost bit of knowledge.`,
            `I like keeping secrets and won't share them with anyone.`,
        ]
    },
    {
        name: 'House Agent',
        personalities: [
            `I'm always looking to improve efficiency.`,
            `I love to share trivia about my house's business.`,
            `I never forget an insult against me or my house.`,
            `I'm enthusiastic about everything my house does.`,
            `I represent my house and take pride in my looks.`,
            `I'm critical of monarchies and limits on the houses.`,
        ],        
        ideals: [
            `Common Good. My house serves a vital function, and its prosperity will help everyone. (Good)`,
            `Tradition. I uphold traditions of my house and bring honor to my family. (Lawful)`,
            `Innovation. Abandon old traditions and find better ways to do things. (Chaotic)`,
            `Power. I want to ensure the prosperity of my house and wield its power myself. (Evil)`,
            `Discovery. I want to learn all I can, both for my house and for my own curiosity. (Any)`,
            `Comfort. I want to ensure that me and mine enjoy the best things in life. (Any)`,
        ],  
        bonds: [
            `My house is my family. I would do anything for it.`,
            `I love someone from another house, but the relationship is forbidden.`,
            `Someone I love was killed by a rival faction within my house, and I will have revenge.`,
            `I don't care about the house as a whole, but I would do anything for my old mentor.`,
            `My house must evolve, and I'll lead the evolution.`,
            `I'm determined to impress the leaders of my house, and to become a leader myself.`,
        ],
        flaws: [
            `I'm fixated on following official protocols.`,
            `I'm obsessed with conspiracy theories and worried about secret societies and hidden demons.`,
            `My house and blood line make me the best!`,
            `My secret could get me expelled from my house.`,
            `My religious beliefs aren't widespread in my house.`,
            `I'm working for a hidden faction in my house that gives me secret assignments.`,
        ]
    },
    {
        name: 'Knight',
        personalities: [
            `My eloquent flattery makes everyone I talk to feel like the most wonderful and important person in the world.`,
            `The common folk love me for my kindness and generosity.`,
            `No one could doubt by looking at my regal bearing that I am a cut above the unwashed masses.`,
            `I take great pains to always look my best and follow the latest fashions.`,
            `I don't like to get my hands dirty, and I won't be caught dead in unsuitable accommodations.`,
            `Despite my noble birth, I do not place myself above other folk. We all have the same blood.`,
            `My favor, once lost, is lost forever.`,
            `If you do me an injury, I will crush you, ruin your name, and salt your fields.`,
        ],        
        ideals: [
            `Respect. Respect is due to me because of my position, but all people regardless of station deserve to be treated with dignity. (Good)`,
            `Responsibility. It is my duty to respect the authority of those above me, just as those below me must respect mine. (Lawful)`,
            `Independence. I must prove that I can handle myself without the coddling of my family. (Chaotic)`,
            `Power. If I can attain more power, no one will tell me what to do. (Evil)`,
            `Family. Blood runs thicker than water. (Any)`,
            `Noble Obligation. It is my duty to protect and care for the people beneath me. (Good)`,
        ],  
        bonds: [
            `I will face any challenge to win the approval of my family.`,
            `My house's alliance with another noble family must be sustained at all costs.`,
            `Nothing is more important than the other members of my family.`,
            `I am in love with the heir of a family that my family despises.`,
            `My loyalty to my sovereign is unwavering.`,
            `The common folk must see me as a hero of the people.`,
        ],
        flaws: [
            `I secretly believe that everyone is beneath me.`,
            `I hide a truly scandalous secret that could ruin my family forever.`,
            `I too often hear veiled insults and threats in every word addressed to me, and I'm quick to anger.`,
            `I have an insatiable desire for carnal pleasures.`,
            `In fact, the world does revolve around me.`,
            `By my words and actions, I often bring shame to my family.`,
        ]
    },
    {
        name: 'Marine',
        personalities: [
            `I speak rarely but mean every word I say.`,
            `I laugh loudly and see the humor in stressful situations.`,
            `I prefer to solve problems without violence, but I finish fights decisively.`,
            `I enjoy being out in nature; poor weather never sours my mood.`,
            `I am dependable.`,
            `I am always working on some project or other.`,
            `I become cantankerous and quiet in the rain.`,
            `When the sea is within my sight, my mood is jovial and optimistic.`,
        ],        
        ideals: [
            `Teamwork. Success depends on cooperation and communication. (Good)`,
            `Code. The marines' code provides a solution for every problem, and following it is imperative. (Lawful)`,
            `Embracing. Life is messy. Throwing yourself into the worst of it is necessary to get the job done. (Chaotic)`,
            `Might. The strong train so that they might rule those who are weak. (Evil)`,
            `Bravery. To act when others quake in fear- this is the essence of the warrior. (Any)`,
            `Perseverance. No injury or obstacle can turn me from my goal. (Any)`,
        ],  
        bonds: [
            `I face danger and evil to offset an unredeemable act in my past.`,
            `I. Will. Finish. The. Job.`,
            `I must set an example of hope for those who have given up.`,
            `I'm searching for a fellow marine captured by an elusive enemy.`,
            `Fear leads to tyranny, and both must be eradicated.`,
            `My commander betrayed my unit, and I will have revenge.`,
        ],
        flaws: [
            `I grow combative and unpredictable when I drink.`,
            `I find civilian life difficult and struggle to say the right thing in social situations.`,
            `My intensity can drive others away.`,
            `I hold grudges and have difficulty forgiving others.`,
            `I become irrational when innocent people are hurt.`,
            `I sometimes stay up all night listening to the ghosts of my fallen enemies.`,
        ]
    },
    {
        name: 'Noble',
        personalities: [
            `My eloquent flattery makes everyone I talk to feel like the most wonderful and important person in the world.`,
            `The common folk love me for my kindness and generosity.`,
            `No one could doubt by looking at my regal bearing that I am a cut above the unwashed masses.`,
            `I take great pains to always look my best and follow the latest fashions.`,
            `I don't like to get my hands dirty, and I won't be caught dead in unsuitable accommodations.`,
            `Despite my noble birth, I do not place myself above other folk. We all have the same blood.`,
            `My favor, once lost, is lost forever.`,
            `If you do me an injury, I will crush you, ruin your name, and salt your fields.`,
        ],        
        ideals: [
            `Respect. Respect is due to me because of my position, but all people regardless of station deserve to be treated with dignity. (Good)`,
            `Responsibility. It is my duty to respect the authority of those above me, just as those below me must respect mine. (Lawful)`,
            `Independence. I must prove that I can handle myself without the coddling of my family. (Chaotic)`,
            `Power. If I can attain more power, no one will tell me what to do. (Evil)`,
            `Family. Blood runs thicker than water. (Any)`,
            `Noble Obligation. It is my duty to protect and care for the people beneath me. (Good)`,
        ],  
        bonds: [
            `I will face any challenge to win the approval of my family.`,
            `My house's alliance with another noble family must be sustained at all costs.`,
            `Nothing is more important than the other members of my family.`,
            `I am in love with the heir of a family that my family despises.`,
            `My loyalty to my sovereign is unwavering.`,
            `The common folk must see me as a hero of the people.`,
        ],
        flaws: [
            `I secretly believe that everyone is beneath me.`,
            `I hide a truly scandalous secret that could ruin my family forever.`,
            `I too often hear veiled insults and threats in every word addressed to me, and I'm quick to anger.`,
            `I have an insatiable desire for carnal pleasures.`,
            `In fact, the world does revolve around me.`,
            `By my words and actions, I often bring shame to my family.`,
        ]
    },
    {
        name: 'Outlander',
        personalities: [
            `I'm driven by a wanderlust that led me away from home.`,
            `I watch over my friends as if they were a litter of newborn pups.`,
            `I once ran twenty-five miles without stopping to warn my clan of an approaching orc horde. I'd do it again if I had to.`,
            `I have a lesson for every situation, drawn from observing nature.`,
            `I place no stock in wealthy or well-mannered folk. Money and manners won't save you from a hungry owlbear.`,
            `I'm always picking things up, absently fiddling with them, and sometimes accidentally breaking them.`,
            `I feel far more comfortable around animals than people.`,
            `I was, in fact, raised by wolves.`,
        ],        
        ideals: [
            `Change. Life is like the seasons, in constant change, and we must change with it. (Chaotic)`,
            `Greater Good. It is each person's responsibility to make the most happiness for the whole tribe. (Good)`,
            `Honor. If I dishonor myself, I dishonor my whole clan. (Lawful)`,
            `Might. The strongest are meant to rule. (Evil)`,
            `Nature. The natural world is more important than all the constructs of civilization. (Neutral)`,
            `Glory. I must earn glory in battle, for myself and my clan. (Any)`,
        ],  
        bonds: [
            `My family, clan, or tribe is the most important thing in my life, even when they are far from me.`,
            `An injury to the unspoiled wilderness of my home is an injury to me.`,
            `I will bring terrible wrath down on the evildoers who destroyed my homeland.`,
            `I am the last of my tribe, and it is up to me to ensure their names enter legend.`,
            `I suffer awful visions of a coming disaster and will do anything to prevent it.`,
            `It is my duty to provide children to sustain my tribe.`,
        ],
        flaws: [
            `I am too enamored of ale, wine, and other intoxicants.`,
            `There's no room for caution in a life lived to the fullest.`,
            `I remember every insult I've received and nurse a silent resentment toward anyone who's ever wronged me.`,
            `I am slow to trust members of other races, tribes, and societies.`,
            `Violence is my answer to almost any challenge.`,
            `Don't expect me to save those who can't save themselves. It is nature's way that the strong thrive and the weak perish.`,
        ]
    },
    {
        name: 'Pirate',
        personalities: [
            `My friends know they can rely on me, no matter what.`,
            `I work hard so that I can play hard when the work is done.`,
            `I enjoy sailing into new ports and making new friends over a flagon of ale.`,
            `I stretch the truth for the sake of a good story.`,
            `To me, a tavern brawl is a nice way to get to know a new city.`,
            `I never pass up a friendly wager.`,
            `My language is as foul as an otyugh nest.`,
            `I like a job well done, especially if I can convince someone else to do it.`,
        ],        
        ideals: [
            `Respect. The thing that keeps a ship together is mutual respect between captain and crew. (Good)`,
            `Fairness. We all do the work, so we all share in the rewards. (Lawful)`,
            `Freedom. The sea is freedom-the freedom to go anywhere and do anything. (Chaotic)`,
            `Mastery. I'm a predator, and the other ships on the sea are my prey. (Evil)`,
            `People. I'm committed to my crewmates, not to ideals. (Neutral)`,
            `Aspiration. Someday I'll own my own ship and chart my own destiny. (Any)`,
        ],  
        bonds: [
            `I'm loyal to my captain first, everything else second.`,
            `The ship is most important - crewmates and captains come and go.`,
            `I'll always remember my first ship.`,
            `In a harbor town, I have a paramour whose eyes nearly stole me from the sea.`,
            `I was cheated out of my fair share of the profits, and I want to get my due.`,
            `Ruthless pirates murdered my captain and crewmates, plundered our ship, and left me to die. Vengeance will be mine.`,
        ],
        flaws: [
            `I follow orders, even if I think they're wrong.`,
            `I'll say anything to avoid having to do extra work.`,
            `Once someone questions my courage, I never back down no matter how dangerous the situation.`,
            `Once I start drinking, it's hard for me to stop.`,
            `I can't help but pocket loose coins and other trinkets I come across.`,
            `My pride will probably lead to my destruction.`,
        ]
    },
    {
        name: 'Rewarded',
        personalities: [
            `A safe home is a foundation on which anything else can be built. (Key, Throne)`,
            `I was elevated to heights I could never otherwise attain, and I won’t waste my fortune. (Star, Sun)`,
            `I try to be a source of inspiration and joy to others. Life is never as bad as you think! (Euryale, Jester)`,
            `Courage and boldness can carry the day when all else fails. (Comet, Knight)`,
            `My good fortune means I can lift others up as well. (Gem, Moon)`,
            `Having the right answers is the first step to solving any problem, no matter how dire. (Fates, Sage)`,
        ],
    },
    {
        name: 'Ruined',
        personalities: [
            `I’ve changed from my past, and I work to live up to my new path. (Balance, Throne)`,
            `Every moment is a gift I refuse to squander. (Euryale, Skull)`,
            `Now that I’ve overcome having nothing, I can survive anything. (Fool, Ruin, Talons)`,
            `I know enemies are set against me, and I always prepare for the worst. (Flames, Rogue)`,
            `I interpret every event as part of a larger pattern I just haven’t worked out yet. (Puzzle, Star)`,
            `I must make up for so much time I’ve already lost. (Donjon, Void)`,
        ],
    },
    {
        name: 'Rune Carver',
        personalities: [
            `Is it practical to learn an ancient language that is rarely spoken? No. But is it fun? Very.`,
            `I learned one of my ancestors was a lauded rune carver whose story was lost to time. I seek to rekindle that legacy.`,
            `The old, traditional markings of runecraft look so boring. Why not give my runes some flair?`,
            `In my studies of runes, I strive to understand how great civilizations of the past fell, so that I may prevent it from happening to societies of the present.`,
            `Life may be a whirlwind of chaos around me, but whenever I create my runes, I feel at peace.`,
            `My brain struggles to process ink words written on paper, but the tactile feeling of carved runes makes my mind sing.`,
        ],
    },
    {
        name: 'Sage',
        personalities: [
            `I use polysyllabic words that convey the impression of great erudition.`,
            `I've read every book in the world's greatest libraries – or I like to boast that I have.`,
            `I'm used to helping out those who aren't as smart as I am, and I patiently explain anything and everything to others.`,
            `There's nothing I like more than a good mystery.`,
            `I'm willing to listen to every side of an argument before I make my own judgment.`,
            `I… speak… slowly… when talking… to idiots,… which… almost… everyone… is… compared… to me.`,
            `I am horribly, horribly awkward in social situations.`,
            `I'm convinced that people are always trying to steal my secrets.`,
        ],        
        ideals: [
            `Knowledge. The path to power and self-improvement is through knowledge. (Neutral)`,
            `Beauty. What is beautiful points us beyond itself toward what is true. (Good)`,
            `Logic. Emotions must not cloud our logical thinking. (Lawful)`,
            `No Limits. Nothing should fetter the infinite possibility inherent in all existence. (Chaotic)`,
            `Power. Knowledge is the path to power and domination. (Evil)`,
            `Self-Improvement. The goal of a life of study is the betterment of oneself. (Any)`,
        ],  
        bonds: [
            `It is my duty to protect my students.`,
            `I have an ancient text that holds terrible secrets that must not fall into the wrong hands.`,
            `I work to preserve a library, university, scriptorium, or monastery.`,
            `My life's work is a series of tomes related to a specific field of lore.`,
            `I've been searching my whole life for the answer to a certain question.`,
            `I sold my soul for knowledge. I hope to do great deeds and win it back.`,
        ],
        flaws: [
            `I am easily distracted by the promise of information.`,
            `Most people scream and run when they see a demon. I stop and take notes on its anatomy.`,
            `Unlocking an ancient mystery is worth the price of a civilization.`,
            `I overlook obvious solutions in favor of complicated ones.`,
            `I speak without really thinking through my words, invariably insulting others.`,
            `I can't keep a secret to save my life, or anyone else's.`,
        ]
    },
    {
        name: 'Sailor',
        personalities: [
            `My friends know they can rely on me, no matter what.`,
            `I work hard so that I can play hard when the work is done.`,
            `I enjoy sailing into new ports and making new friends over a flagon of ale.`,
            `I stretch the truth for the sake of a good story.`,
            `To me, a tavern brawl is a nice way to get to know a new city.`,
            `I never pass up a friendly wager.`,
            `My language is as foul as an otyugh nest.`,
            `I like a job well done, especially if I can convince someone else to do it.`,
        ],        
        ideals: [
            `Respect. The thing that keeps a ship together is mutual respect between captain and crew. (Good)`,
            `Fairness. We all do the work, so we all share in the rewards. (Lawful)`,
            `Freedom. The sea is freedom-the freedom to go anywhere and do anything. (Chaotic)`,
            `Mastery. I'm a predator, and the other ships on the sea are my prey. (Evil)`,
            `People. I'm committed to my crewmates, not to ideals. (Neutral)`,
            `Aspiration. Someday I'll own my own ship and chart my own destiny. (Any)`,
        ],  
        bonds: [
            `I'm loyal to my captain first, everything else second.`,
            `The ship is most important - crewmates and captains come and go.`,
            `I'll always remember my first ship.`,
            `In a harbor town, I have a paramour whose eyes nearly stole me from the sea.`,
            `I was cheated out of my fair share of the profits, and I want to get my due.`,
            `Ruthless pirates murdered my captain and crewmates, plundered our ship, and left me to die. Vengeance will be mine.`,
        ],
        flaws: [
            `I follow orders, even if I think they're wrong.`,
            `I'll say anything to avoid having to do extra work.`,
            `Once someone questions my courage, I never back down no matter how dangerous the situation.`,
            `Once I start drinking, it's hard for me to stop.`,
            `I can't help but pocket loose coins and other trinkets I come across.`,
            `My pride will probably lead to my destruction.`,
        ]
    },
    {
        name: 'Shipwright',
        personalities: [
            `I love talking and being heard more than I like to listen.`,
            `I'm extremely fond of puzzles.`,
            `I thrive under pressure.`,
            `I love sketching and designing objects, especially boats.`,
            `I'm not afraid of hard work—in fact, I prefer it.`,
            `A pipe, an ale, and the smell of the sea: paradise.`,
            `I have an endless supply of cautionary tales related to the sea.`,
            `I don't mind getting my hands dirty.`,
        ],        
        ideals: [
            `Crew. If everyone on deck pitches in, we'll never sink. (Good)`,
            `Careful Lines. A ship must be balanced according to the laws of the universe. (Lawful)`,
            `Invention. Make what you need out of whatever is at hand. (Chaotic)`,
            `Perfection. To measure a being and find it lacking is the greatest disappointment. (Evil)`,
            `Reflection. Muddied water always clears in time. (Any)`,
            `Hope. The horizon at sea holds the greatest promise. (Any)`,
        ],  
        bonds: [
            `I must visit all the oceans of the world and behold the ships that sail there.`,
            `Much of the treasure I claim will be used to enrich my community.`,
            `I must find a kind of wood rumored to possess magical qualities.`,
            `I repair broken things to redeem what's broken in myself.`,
            `I will craft a boat capable of sailing through the most dangerous of storms.`,
            `A kraken destroyed my masterpiece; its teeth shall adorn my hearth.`,
        ],
        flaws: [
            `I don't know when to throw something away. You never know when it might be useful again.`,
            `I get frustrated to the point of distraction by shoddy craftsmanship.`,
            `Though I am an excellent crafter, my work tends to look as though it belongs on a ship.`,
            `I am so obsessed with sketching my ideas for elaborate inventions that I sometimes forget little thing like eating and sleeping.`,
            `I'm judgmental of those who are not skilled with tools of some kind.`,
            `I sometimes take things that don't belong to me, especially if they are very well made.`,
        ]
    },
    {
        name: 'Smuggler',
        personalities: [
            `I love being on the water but hate fishing.`,
            `I think of everything in terms of monetary value.`,
            `I never stop smiling.`,
            `Nothing rattles me; I have a lie for every occasion.`,
            `I love gold but won't cheat a friend.`,
            `I enjoy doing things others believe to be impossible.`,
            `I become wistful when I see the sun rise over the ocean.`,
            `I am no common criminal; I am a mastermind.`,
        ],        
        ideals: [
            `Wealth Heaps of coins in a secure vault is all I dream of. (Any)`,
            `Smuggler's Code I uphold the unwritten rules of the smugglers, who do not cheat one another or directly harm innocents. (Lawful)`,
            `All for a Coin I'll do nearly anything if it means I turn a profit. (Evil)`,
            `Peace and Prosperity I smuggle only to achieve a greater goal that benefits my community. (Good)`,
            `People For all my many lies, I place a high value on friendship. (Any)`,
            `Daring I am most happy when risking everything. (Any)`,
        ],  
        bonds: [
            `My vessel was stolen from me, and I burn with the desire to recover it.`,
            `I intend to become the leader of the network of smugglers that I belong to.`,
            `I owe a debt that cannot be repaid in gold.`,
            `After one last job, I will retire from the business.`,
            `I was tricked by a fellow smuggler who stole something precious from me. I will find that thief.`,
            `I give most of my profits to a charitable cause, and I don't like to brag about it.`,
        ],
        flaws: [
            `Lying is reflexive, and I sometimes engage in it without realizing.`,
            `I tend to assess my relationships in terms of profit and loss.`,
            `I believe everyone has a price and am cynical toward those who present themselves as virtuous.`,
            `I struggle to trust the words of others.`,
            `Few people know the real me.`,
            `Though I act charming, I feel nothing for others and don't know what friendship is.`,
        ]
    },
    {
        name: 'Soldier',
        personalities: [
            `I'm always polite and respectful.`,
            `I'm haunted by memories of war. I can't get the images of violence out of my mind.`,
            `I've lost too many friends, and I'm slow to make new ones.`,
            `I'm full of inspiring and cautionary tales from my military experience relevant to almost every combat situation.`,
            `I can stare down a hell hound without flinching.`,
            `I enjoy being strong and like breaking things.`,
            `I have a crude sense of humor.`,
            `I face problems head-on. A simple, direct solution is the best path to success.`,
        ],        
        ideals: [
            `Greater Good. Our lot is to lay down our lives in defense of others. (Good)`,
            `Responsibility. I do what I must and obey just authority. (Lawful)`,
            `Independence. When people follow orders blindly, they embrace a kind of tyranny. (Chaotic)`,
            `Might. In life as in war, the stronger force wins. (Evil)`,
            `Live and Let Live. Ideals aren't worth killing over or going to war for. (Neutral)`,
            `Nation. My city, nation, or people are all that matter. (Any)`,
        ],  
        bonds: [
            `I would still lay down my life for the people I served with.`,
            `Someone saved my life on the battlefield. To this day, I will never leave a friend behind.`,
            `My honor is my life.`,
            `I'll never forget the crushing defeat my company suffered or the enemies who dealt it.`,
            `Those who fight beside me are those worth dying for.`,
            `I fight for those who cannot fight for themselves.`,
        ],
        flaws: [
            `The monstrous enemy we faced in battle still leaves me quivering with fear.`,
            `I have little respect for anyone who is not a proven warrior.`,
            `I made a terrible mistake in battle that cost many lives - and I would do anything to keep that mistake secret.`,
            `My hatred of my enemies is blind and unreasoning.`,
            `I obey the law, even if the law causes misery.`,
            `I'd rather eat my armor than admit when I'm wrong.`,
        ]
    },
    {
        name: 'Spy',
        personalities: [
            `I always have a plan for what to do when things go wrong.`,
            `I am always calm, no matter what the situation. I never raise my voice or let my emotions control me.`,
            `The first thing I do in a new place is note the locations of everything valuable – or where such things could be hidden.`,
            `I would rather make a new friend than a new enemy.`,
            `I am incredibly slow to trust. Those who seem the fairest often have the most to hide.`,
            `I don't pay attention to the risks in a situation. Never tell me the odds.`,
            `The best way to get me to do something is to tell me I can't do it.`,
            `I blow up at the slightest insult.`,
        ],        
        ideals: [
            `Honor. I don't steal from others in the trade. (Lawful)`,
            `Freedom. Chains are meant to be broken, as are those who would forge them. (Chaotic)`,
            `Charity. I steal from the wealthy so that I can help people in need. (Good)`,
            `Greed. I will do whatever it takes to become wealthy. (Evil)`,
            `People. I'm loyal to my friends, not to any ideals, and everyone else can take a trip down the Styx for all I care. (Neutral)`,
            `Redemption. There's a spark of good in everyone. (Good)`,
        ],  
        bonds: [
            `I'm trying to pay off an old debt I owe to a generous benefactor.`,
            `My ill-gotten gains go to support my family.`,
            `Something important was taken from me, and I aim to steal it back.`,
            `I will become the greatest thief that ever lived.`,
            `I'm guilty of a terrible crime. I hope I can redeem myself for it.`,
            `Someone I loved died because of I mistake I made. That will never happen again.`,
        ],
        flaws: [
            `When I see something valuable, I can't think about anything but how to steal it.`,
            `When faced with a choice between money and my friends, I usually choose the money.`,
            `If there's a plan, I'll forget it. If I don't forget it, I'll ignore it.`,
            `I have a "tell" that reveals when I'm lying.`,
            `I turn tail and run when things look bad.`,
            `An innocent person is in prison for a crime that I committed. I'm okay with that.`,
        ]
    },
    {
        name: 'Urchin',
        personalities: [
            `I hide scraps of food and trinkets away in my pockets.`,
            `I ask a lot of questions.`,
            `I like to squeeze into small places where no one else can get to me.`,
            `I sleep with my back to a wall or tree, with everything I own wrapped in a bundle in my arms.`,
            `I eat like a pig and have bad manners.`,
            `I think anyone who's nice to me is hiding evil intent.`,
            `I don't like to bathe.`,
            `I bluntly say what other people are hinting at or hiding.`,
        ],        
        ideals: [
            `Respect. All people, rich or poor, deserve respect. (Good)`,
            `Community. We have to take care of each other, because no one else is going to do it. (Lawful)`,
            `Change. The low are lifted up, and the high and mighty are brought down. Change is the nature of things. (Chaotic)`,
            `Retribution. The rich need to be shown what life and death are like in the gutters. (Evil)`,
            `People. I help the people who help me-that's what keeps us alive. (Neutral)`,
            `Aspiration. I'm going to prove that I'm worthy of a better life. (Any)`,
        ],  
        bonds: [
            `My town or city is my home, and I'll fight to defend it.`,
            `I sponsor an orphanage to keep others from enduring what I was forced to endure.`,
            `I owe my survival to another urchin who taught me to live on the streets.`,
            `I owe a debt I can never repay to the person who took pity on me.`,
            `I escaped my life of poverty by robbing an important person, and I'm wanted for it.`,
            `No one else should have to endure the hardships I've been through.`,
        ],
        flaws: [
            `If I'm outnumbered, I will run away from a fight.`,
            `Gold seems like a lot of money to me, and I'll do just about anything for more of it.`,
            `I will never fully trust anyone other than myself.`,
            `I'd rather kill someone in their sleep then fight fair.`,
            `It's not stealing if I need it more than someone else.`,
            `People who can't take care of themselves get what they deserve.`,
        ]
    },
    {
        name: 'Witchlight Hand',
        personalities: [
            `I'm haunted by fey laughter that only I can hear, though I know it's just my mind playing tricks on me.`,
            `Like a nomad, I can't settle down in one place for very long.`,
            `Good music makes me weep like a baby.`,
            `Wherever I go, I try to bring a little of the warmth and tranquility of home with me.`,
            `I have never lost my childlike sense of wonder.`,
            `When I have a new idea, I get wildly excited about it until I come up with another, better idea.`,
            `I live by my own set of weird and wonderful rules.`,
            `I can't bring myself to trust most adults.`,
        ],        
        ideals: [
            `Friendship. I never leave a friend behind. (Good)`,
            `Empathy. No creature should be made to suffer. (Good)`,
            `Wanderlust. I prefer to take the less traveled path. (Chaotic)`,
            `Changeability. Change is good, which is why I live by an ever-changing set of rules. (Chaotic)`,
            `Honor. A deal is a deal, and I would never break one. (Lawful)`,
            `Rule of Three. Everything in the multiverse happens in threes. I see the "rule of three" everywhere. (Lawful)`,
            `Obsession. I won't let go of a grudge. (Evil)`,
            `Greed. I will do whatever it takes to get what I want, regardless of the harm it might cause. (Evil)`,
        ],  
        bonds: [
            `I would never break my word.`,
            `I find magic in all its forms to be compelling. The more magical a place, the more I am drawn to it.`,
            `I do what I can to protect the natural world.`,
            `A trusted friend is the most important thing in the multiverse to me.`,
            `I can't bring myself to harm a Fey creature, either because I consider myself one or because I fear the repercussions.`,
            `The Witchlight Carnival feels like home to me.`,
            `I'm drawn to the Feywild and long to return there, if only for a short while.`,
            `I feel indebted to Mister Witch and Mister Light for giving me a home and a purpose.`,
        ],
        flaws: [
            `I easily lose track of time. My poor sense of time means I'm always late.`,
            `I think the whole multiverse is out to get me.`,
            `I'm always operating under a tight timeline, and I'm obsessed with keeping everything on schedule.`,
            `I'm a kleptomaniac who covets shiny, sparkling treasure.`,
            `I'm forgetful. Sometimes I can't remember even the simplest things.`,
            `I never give away anything for free and always expect something in return.`,
            `I have many vices and tend to indulge them.`,
            `I'm always changing my mind-well, almost always.`,
        ]
    },
  
]

export default backgrounds